export default {
    data:[
        {
            heading: "公安",
            headSum:[
                {
                    val:[
                        {id:1,item:"公安"},
                        {id:2,item:"出入境"},
                        {id:3,item:"交管"},
                        {id:4,item:"治安局"}
                    ],
                    subSet:[
                        [
                            {name:"户籍证明",img:require("@/img/list/huji1.png"),url:"/huosehold/householdWindow"},
                            {name:"户口注销证明",img:require("@/img/list/hukou1.png"),url:"/publicSecurity/AccountCancellation"},
                            {name:"公民身份号码变更更正证明",img:require("@/img/list/gongmin1.png"),url:"/publicSecurity/cardid"},
                            {name:"户口变更证明",img:require("@/img/list/hukou2.png"),url:"/publicSecurity/certificateid"},
                            {name:"亲属关系证明",img:require("@/img/list/qinshu1.png"),url:"/publicSecurity/relationship"}
                        ],
                        [
                            {name:"办理往来港澳通行证个人游签注",img:require("@/img/list/a1.png"),url:"/entyDndexitPage/entryindividual"},
                            {name:"办理往来港澳通行证团队游签注",img:require("@/img/list/a2.png"),url:"/entyDndexitPage/entryDndexit"},
                            {name:"港澳通行证剩余签注次数查询",img:require("@/img/list/a3.png"),url:"/macaoPermit/macaoPermitHome"},
                            {name:"办理往来台湾通行证个人游签注",img:require("@/img/list/a4.png"),url:"/entyDndexitPage/TWIndividualLogin"},
                            {name:"办理往来台湾通行证团队游签注",img:require("@/img/list/tw5.png"),url:"/entyDndexitPage/TWDndexit"},
                            {name:"台湾通行证剩余签注次数查询",img:require("@/img/list/a5.png"),url:"/TWPermit/TWPermitHome"},   
                        ],
                        [
                            {name:"驾驶人交通违法查询",img:require("@/img/list/a6.png"),url:"/jiaotongfa/driverInquireCommon/InquireLogin"},   
                            {name:"驾驶人交通违法查询和处理",img:require("@/img/list/a7.png"),url:"/jiaotongfa/jiaotong/c1"},   
                            {name:"机动车交通违法查询和处理",img:require("@/img/list/a8.png"),url:"/jiaotongfa/carCheckCommon/carCheck"},   
                            {name:"驾驶证扣分查询",img:require("@/img/list/a9.png"),url:"/jiaotongfa/deductMarksCommon/marksLogin"},   
                            {name:"机动车驾驶证有效期满换证",img:require("@/img/list/jdc6.png"),url:"/jiaotongfa/validtyCommon/validtyCheck"},   
                            {name:"机动车驾驶证转入换证",img:require("@/img/list/jdc7.png"),url:"/jiaotongfa/motorCommon/periodCheck"},   
                            {name:"机动车驾驶证达到规定年龄换证",img:require("@/img/list/jdc8.png"),url:"/jiaotongfa/renewalAge"},   
                            {name:"机动车驾驶证自愿降低准驾车型换证",img:require("@/img/list/jdc9.png"),url:"/jiaotongfa/renewalReduce"},   
                            {name:"机动车驾驶证遗失补证",img:require("@/img/list/jdc10.png"),url:"/jiaotongfa/driverReplaceCommon/replaceCheck"},   
                            {name:"驾驶人审验(不含校车驾驶人)",img:require("@/img/list/jdc11.png"),url:"/jiaotongfa/driverInspect"}, 
                        ],
                        [
                            {name:"申报居住登记",img:require("@/img/list/a10.png"),url:"/residenceAudit"},   
                            {name:"申领居住证",img:require("@/img/list/a11.png"),url:"/residenceApply"},   
                            {name:"签注居住证",img:require("@/img/list/a13.png"),url:"/endorsementres"},   
                            {name:"补领、换领居住证",img:require("@/img/list/a14.png"),url:"/residenceReplace"},   
                            {name:"无犯罪记录证明",img:require("@/img/list/a15.png"),url:"/crimeTestify/crimeTStep0"},   
                        ]
                    ]
                },
            ],
            leftId:0
        },
        {
            heading: "人社",
            headSum:[
                {
                    subSet:[
                        [
                        {name:"社会保险参保证明",img:require("@/img/list/a16.png"),url:"/ssprinting/Proofof"},
                        {name:"社保清单打印",img:require("@/img/list/a17.png"),url:"/ssprinting/psetp"},
                        {name:"社保卡金融账户余额查询",img:require("@/img/list/a18.png"),url:"/ssprinting/balance"},
                        {name:"社保个人基本资料查询",img:require("@/img/list/a19.png"),url:"/ssprinting/basicquery"},
                        {name:"社保待遇发放信息查询",img:require("@/img/list/a21.png"),url:"/ssprinting/grant"},
                        {name:"基本养老金领取资格认证（生存认证）",img:require("@/img/list/a22.png"),url:"/ssprinting/basicOldAge"}
                        ]
                    ]
                },
            ],
            leftId:1
        },
        {
            heading: "民政",
            headSum:[
                {
                    subSet:[
                        [
                            {name:"最低生活保障预约申请",img:require("@/img/list/a23.png"),url:"/safeguardEntrance"},
                            {name:"老年人社会保障（优待）卡申领",img:require("@/img/list/a24.png"),url:"/socialEntrance"},
                            {name:"高龄老人津贴发放资格",img:require("@/img/list/a25.png"),url:"/advancedEntrance"},
                        ]
                    ]
                },
            ],
            leftId:1
        },
        {
            heading: "税务",
            headSum:[
                {
                    subSet:[
                        [
                            {name:"个税清单打印",img:require("@/img//list/shui01.png"),url:"/taxation/individualtaxList"},
                            {name:"个税完税证明打印",img:require("@/img/list/shui02.png"),url:"/taxation/individualtaxProve"},
                            //{name:"个人其他税费证明打印",img:require("@/img/list/shui03.png"),url:"/taxation/individualtaxOther"},
                            //{name:"车船税缴纳",img:require("@/img/list/shui04.png"),url:"/taxation/boatcartTax"},
                        ]
                    ]
                },
            ],
            leftId:1
        },
        {
            heading: "司法",
            headSum:[
                {
                    subSet:[
                        [
                            {name:"律师有偿服务",img:require("@/img/list/lushi2.png"),url:"/paidservice/pas1"},
                            {name:"法律文书查询",img:require("@/img/list/falu1.png"),url:"/enquiry/enquiry"},
                        ]
                    ]
                },
            ],
            leftId:1
        },
        {
            heading: "住建",
            headSum:[
                {
                    subSet:[
                        [
                            {name:"公积金查询",img:require("@/img/list/a32.png"),url:"/query"},
                            {name:"公积金缴存信息",img:require("@/img/list/a33.png"),url:"/inform"},
                            {name:"公积金缴存明细",img:require("@/img/list/a34.png"),url:"/hand"},
                        ]
                    ]
                },
            ],
            leftId:1
        },
        {
            heading: "残联",
            headSum:[
                {
                    subSet:[
                        [
                            {name:"残疾人证申请办理",img:require("@/img/list/a35.png"),url:"/pmUion/CJRZBBFn"},
                            {name:"残疾人证基本信息变更",img:require("@/img/list/a20.png"),url:"/pmUion/CJRZSChangeFn"},
                            {name:"残疾人证补办",img:require("@/img/list/a21.png"),url:"/pmUion/CJRapply"},
                            {name:"南粤扶残助学",img:require("@/img/list/a22.png"),url:"/pmUion/supportAidStudy"},
                            {name:"残疾人证注销",img:require("@/img/list/a23.png"),url:"/pmUion/lisenceCancellation"},
                        ]
                    ]
                },
            ],
            leftId:1
        }
    ]
}